{{- /* Check for required environment */ -}}
{{- if not (env "MINIKUBE_GATEWAY") -}}
  {{- fail "\n---\nMINIKUBE_GATEWAY env var must be set! Use your `localkube_env` shell function to set it." -}}
{{- end -}}
{{- /* Set global template variables for use in any individual YAML object in this file */ -}}
{{- $appName      := "tpe_prebid_service" -}}
{{- /* trunc 55 instead of 63 to allow for ssh and modules volumes */ -}}
{{- $dnsName          := $appName | replace "_" "-" | trunc 63 -}}
{{- $env              := "development" -}}
{{- $labels           := printf "app: %q\nenv: %q" $appName $env -}}
{{- $registry         := "localhost:5000" -}}
{{- $appImage         := printf "%v/%v/%v:%v" $registry "tapjoy" $appName "baseimage" -}}
{{- $dataDir          := "/data" -}}
{{- $appPort          := 8000 -}}
---
########################################################################################################################
## NETWORK-RELATED MANIFESTS
########################################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels  | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ $labels | nindent 4 }}
  ports:
  - name: app
    port: 80
    targetPort: {{$appPort}}
---
########################################################################################################################
## STORAGE-RELATED MANIFESTS
########################################################################################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels | nindent 4 }}
spec:
  capacity:
    storage: 15Gi # Required setting. Arbitrarily chosen advertised storage capacity.
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: {{ env "MINIKUBE_GATEWAY" | quote }}
    path: {{ env "PWD" | quote }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels | nindent 4 }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi # Required setting. Matches the advertised capacity of the PersistentVolume.
---
########################################################################################################################
## CONFIGURATION-RELATED MANIFESTS
########################################################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels | nindent 4 }}
data:
  # Placeholder until we need some real ENV for the application
  RACK_ENV: {{ $env | quote }} 

  PBS_MONITORING_NEWRELIC_LICENSE_KEY: {{ default "bb8353602ba48d962a5db59ac4e1468d2da7fb8d" (env "NEW_RELIC_LICENSE_KEY") | quote }}
  PBS_MONITORING_NEWRELIC_DEBUG_MODE: "false"
---
########################################################################################################################
## WORKLOAD-RELATED MANIFESTS
########################################################################################################################
apiVersion: v1
kind: Pod
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels | nindent 4 }}
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: app
    image: {{ $appImage | quote }}
    imagePullPolicy: Never # We rebuild the baseimage on every `make dev`
    command: ["./deploy/local/entrypoint.sh"]
    # command: ["tail","-f","/dev/null","--"] # Use this as an escape hatch if your app is crashing on turnup
    args: ["prepare_and_run make run"]
    envFrom:
    - configMapRef:
        name: {{ $dnsName | quote }}
    ports:
      - name: app
        containerPort: {{ $appPort }}
        protocol: TCP
    volumeMounts:
      - name: src
        mountPath: {{ list "/go/src" "github.com/tapjoy" $appName | join "/" | quote }}
    readinessProbe:
      httpGet:
        path: /healthz
        port: {{$appPort}}
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
  - name: src
    persistentVolumeClaim:
      claimName: {{ $dnsName | quote }}
---
